let DraggableCapsule = {
	create: function(isAttrAutoGenerated, isAttrOriginallyNominal) {
		let capsuleClassName = '';
		let draggableCapsuleHTML = '';

		if (isAttrAutoGenerated)
			capsuleClassName += ' auto-generated';
		if (isAttrOriginallyNominal)
			capsuleClassName += ' originally-nominal';

		draggableCapsuleHTML = '<div id="draggable-capsule" class="' + capsuleClassName.trim() + '">' +
									'<span class="fa attribute-type"></span>' +
									'<span class="aggregate-or-time-unit"></span>' +
									'<span class="attribute-name"></span>' +
									'<span class="fa fa-cog"></span>' +
									'<span class="fa fa-times"></span>' +
							   '</div>';

		$('body').append(draggableCapsuleHTML);
	},
	remove: function() {
		$('#draggable-capsule')
			.remove();
	},
	isCreated: function() {
		return $('#draggable-capsule').length > 0;
	},
	moveTo: function(top, left) {
		let draggableCapsuleWidth = $('#draggable-capsule').width();
		let draggableCapsuleHeight = $('#draggable-capsule').height();

		$('#draggable-capsule')
			.css('top', top - draggableCapsuleHeight / 2)
			.css('left', left - draggableCapsuleWidth / 2);
	},
	moveTopLeftCornerTo: function(top, left) {
		$('#draggable-capsule')
			.css('top', top)
			.css('left', left);
	},
	changeWidth: function(width) {
		$('#draggable-capsule')
			.css('width', width)
	},

	// change capsule info

	changeAttributeType: function(attributeType) {
		if (attributeType == 'temporal')
			$('#draggable-capsule .attribute-type')
				.addClass('fa-calendar');

		if (attributeType == 'quantitative')
			$('#draggable-capsule .attribute-type')
				.addClass('fa-hashtag');

		if (attributeType == 'nominal' || attributeType == 'ordinal')
			$('#draggable-capsule .attribute-type')
				.addClass('fa-font');
	},
	changeAttributeName: function(attributeName, parenthesis = false) {
		if (parenthesis)
			$('#draggable-capsule .attribute-name')
				.html('<span class="parenthesis">(</span>' + attributeName + '<span class="parenthesis">)</span>');

		if (!parenthesis)
			$('#draggable-capsule .attribute-name')
				.html(attributeName);
	},
	changeAggregateOrTimeUnit: function(aggregateOrTimeUnit) {
		$('#draggable-capsule .aggregate-or-time-unit')
			.html(aggregateOrTimeUnit);
	},
	adjustAttributeNameWidth: function() {
		let attributeNameLength = { short: 110, long: 125 };
		let aggregateOrTimeUnitWidth = $('#draggable-capsule .aggregate-or-time-unit').width();
		let hasRemoveButton = true;
		let hasSettingButton = !$('#draggable-capsule').hasClass('auto-generated') && 
							   !$('#draggable-capsule').hasClass('originally-nominal');
			
		if (hasSettingButton && hasRemoveButton)
			$('#draggable-capsule .attribute-name')
				.css('width', attributeNameLength.short - aggregateOrTimeUnitWidth);

		if (!hasSettingButton && hasRemoveButton)
			$('#draggable-capsule .attribute-name')
				.css('width', attributeNameLength.long - aggregateOrTimeUnitWidth);
	}
}